<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="6bbcb98e-3623-4adc-a987-bf91e960a27b" name="19007364@DEVVMJTLSU56 2011-10-02 21:43:47" runUser="CORP\19007364" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="1bf78725-8af6-4bc5-9a87-d74e52507b22">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="19007364_DEVVMJTLSU56 2011-10-02 21_43_47">
      <DeploymentItem filename="C:\Documents and Settings\19007364\My Documents\Visual Studio 2010\Projects\RhinoMocksDemo\packages\RhinoMocks.3.6\lib\Rhino.Mocks.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2011-10-02T21:43:47.7073628-04:00" queuing="2011-10-02T21:43:50.2386128-04:00" start="2011-10-02T21:43:50.7698628-04:00" finish="2011-10-02T21:43:54.1136128-04:00" />
  <ResultSummary outcome="Completed">
    <Counters total="1" executed="1" passed="1" error="0" failed="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="Functions_Can_Be_Setup_To_Throw_Exception" storage="c:\documents and settings\19007364\my documents\visual studio 2010\projects\rhinomocksdemo\rhinomocksdemo\bin\debug\rhinomocksdemo.dll" id="5affb05b-142a-81b8-ad25-a690868ae30c">
      <Execution id="2f160ac7-e6d4-4799-91f7-4373982944a9" />
      <TestMethod codeBase="C:/Documents and Settings/19007364/My Documents/Visual Studio 2010/Projects/RhinoMocksDemo/RhinoMocksDemo/bin/Debug/RhinoMocksDemo.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="RhinoMocksDemo.AnimalTest, RhinoMocksDemo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="Functions_Can_Be_Setup_To_Throw_Exception" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="5affb05b-142a-81b8-ad25-a690868ae30c" executionId="2f160ac7-e6d4-4799-91f7-4373982944a9" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="2f160ac7-e6d4-4799-91f7-4373982944a9" testId="5affb05b-142a-81b8-ad25-a690868ae30c" testName="Functions_Can_Be_Setup_To_Throw_Exception" computerName="DEVVMJTLSU56" duration="00:00:00.4552262" startTime="2011-10-02T21:43:51.1604878-04:00" endTime="2011-10-02T21:43:53.0979878-04:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Passed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="2f160ac7-e6d4-4799-91f7-4373982944a9">
    </UnitTestResult>
  </Results>
</TestRun>